/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.bioskopapp.admin;

import com.uas.bioskopapp.admin.connect.Konek;
import com.uas.bioskopapp.admin.kelas.Akses;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author User
 */
public class DaftarBooking extends javax.swing.JFrame {

    private String username, pass,namaAdmin, noStudio;
    private Statement ks;
    private ResultSet Rslogin;
    private String sql="";
    private ResultSet Rs;
    private Connection koneksi;
    private Statement cs;
    private Konek kdb = new Konek();
    /**
     * Creates new form DaftarBooking
     */
    public DaftarBooking() {
        initComponents();

        
        studio1.setVisible(false);
        studio2.setVisible(false);
        studio3.setVisible(false);
    

    }

    void namauser(String nama, String password) {
            
            
            try {
            sql = "select * from admin where username='"+nama+"'"
            + "and password='"+password+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rslogin = cs.executeQuery(sql);
            if(Rslogin.next()){
            username = Rslogin.getString("username");
            pass = Rslogin.getString("password");
            namaAdmin = Rslogin.getString("nama");
            }else{
                System.out.println("Tidak ada username");
            }
            } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
                           
    }
    
    void dataTable(DefaultTableModel tabel1, JTable table2){
        tabel1.addColumn("ID");
        tabel1.addColumn("Username"); 
        tabel1.addColumn("Nama Bioskop");
        tabel1.addColumn("Nama Film");
        tabel1.addColumn("Nomor Studio");
        tabel1.addColumn("Tanggal"); 
        tabel1.addColumn("Jam"); 
        
        tabel1.addColumn("Nama Pemesan");
        tabel1.addColumn("Baris");
        tabel1.addColumn("Nomor");
        tabel1.addColumn("Harga");
        tabel1.addColumn("Status"); 
        
        table2.setModel(tabel1);
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biosPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        bioskop1 = new javax.swing.JButton();
        bioskop2 = new javax.swing.JButton();
        bioskop3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filmPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idL = new javax.swing.JLabel();
        userL = new javax.swing.JLabel();
        biosL = new javax.swing.JLabel();
        filmL = new javax.swing.JLabel();
        studioL = new javax.swing.JLabel();
        tglL = new javax.swing.JLabel();
        jamL = new javax.swing.JLabel();
        kursiL = new javax.swing.JLabel();
        napesL = new javax.swing.JLabel();
        statusL = new javax.swing.JLabel();
        hrgL = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namaBios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studio1 = new javax.swing.JButton();
        studio2 = new javax.swing.JButton();
        studio3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        biosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        bioskop1.setText("AMBARRUKMO XXI");
        bioskop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop1ActionPerformed(evt);
            }
        });

        bioskop2.setText("EMPIRE XXI");
        bioskop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop2ActionPerformed(evt);
            }
        });

        bioskop3.setText("JOGJA CITY XXI");
        bioskop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bioskop :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn)
                    .addComponent(bioskop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addComponent(bioskop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bioskop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bioskop1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioskop2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioskop3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Pemesanan Tiket");

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));
        tabelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelFilm);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("ID :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Username :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bioskop :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Film :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Studio :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tanggal :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Jam :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nama Pemesan :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Kursi :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Harga :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Status :");

        idL.setText("-");

        userL.setText("-");

        biosL.setText("-");

        filmL.setText("-");

        studioL.setText("-");

        tglL.setText("-");

        jamL.setText("-");

        kursiL.setText("-");

        napesL.setText("-");

        statusL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statusL.setText("-");

        hrgL.setText("-");

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filmPanelLayout = new javax.swing.GroupLayout(filmPanel);
        filmPanel.setLayout(filmPanelLayout);
        filmPanelLayout.setHorizontalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filmL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5)
                                .addComponent(biosL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tglL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jamL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(filmPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kursiL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(filmPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studioL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(napesL, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmBtn)
                                    .addComponent(hrgL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(200, 200, 200)))
                .addContainerGap())
        );
        filmPanelLayout.setVerticalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(idL)
                    .addComponent(studioL)
                    .addComponent(napesL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(userL)
                    .addComponent(tglL)
                    .addComponent(statusL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11)
                    .addComponent(biosL)
                    .addComponent(jamL)
                    .addComponent(hrgL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(filmL)
                    .addComponent(kursiL)
                    .addComponent(confirmBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bioskop : ");

        namaBios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaBios.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Studio :");

        studio1.setText("Studio1");
        studio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio1ActionPerformed(evt);
            }
        });

        studio2.setText("Studio2");
        studio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2ActionPerformed(evt);
            }
        });

        studio3.setText("Studio3");
        studio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout biosPanelLayout = new javax.swing.GroupLayout(biosPanel);
        biosPanel.setLayout(biosPanelLayout);
        biosPanelLayout.setHorizontalGroup(
            biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biosPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biosPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaBios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(studio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studio3)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(312, 312, 312))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                                .addComponent(filmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        biosPanelLayout.setVerticalGroup(
            biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(biosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio1)
                    .addComponent(jLabel4)
                    .addComponent(studio2)
                    .addComponent(studio3)
                    .addComponent(namaBios)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addComponent(filmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(biosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(biosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio3ActionPerformed
        // TODO add your handling code here:
                biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        noStudio = "3";
        filmPanel.setBackground(Color.orange);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
        try{

            sql="SELECT * FROM  pesan WHERE nama_bioskop LIKE '"+namaBios.getText()+"' AND no_studio LIKE '" +noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8),
                    Rs.getString(9),
                    Rs.getString(10),
                    Rs.getString(11),
                    Rs.getString(12),

                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio3ActionPerformed

    private void studio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio1ActionPerformed
        // TODO add your handling code here:
                biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        noStudio = "1";
        filmPanel.setBackground(Color.white);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
        try{

            sql="SELECT * FROM  pesan WHERE nama_bioskop LIKE '"+namaBios.getText()+"' AND no_studio LIKE '" +noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8),
                    Rs.getString(9),
                    Rs.getString(10),
                    Rs.getString(11),
                    Rs.getString(12),

                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio1ActionPerformed

    private void bioskop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop3ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
                biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        biosPanel.setBackground(Color.pink);
        namaBios.setText("JOGJA CITY XXI");
        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));
        

    }//GEN-LAST:event_bioskop3ActionPerformed

    private void bioskop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop2ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
                biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        biosPanel.setBackground(Color.yellow);
        namaBios.setText("EMPIRE XXI");
                tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));
        
    }//GEN-LAST:event_bioskop2ActionPerformed

    private void bioskop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop1ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
        biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        
        biosPanel.setBackground(Color.green);
        namaBios.setText("AMBARRUKMO XXI");
                tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));
       
    }//GEN-LAST:event_bioskop1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.namauser(username, pass);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void studio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2ActionPerformed
        // TODO add your handling code here:
                biosL.setText("");
        studioL.setText("");
        filmL.setText("");
        idL.setText("");
        userL.setText("");
        hrgL.setText("");
        kursiL.setText("");
        napesL.setText("");
        jamL.setText("");
        statusL.setText("");
        tglL.setText("");
        confirmBtn.setEnabled(false);
        noStudio = "2";
        filmPanel.setBackground(Color.LIGHT_GRAY);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
        try{

            sql="SELECT * FROM  pesan WHERE nama_bioskop LIKE '"+namaBios.getText()+"' AND no_studio LIKE '" +noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8),
                    Rs.getString(9),
                    Rs.getString(10),
                    Rs.getString(11),
                    Rs.getString(12),
                    

                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio2ActionPerformed

    private void tabelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelFilmMouseClicked
        // TODO add your handling code here:
        confirmBtn.setEnabled(true);
        int i = tabelFilm.getSelectedRow();
        TableModel model = tabelFilm.getModel();
        idL.setText(model.getValueAt(i,0).toString());
        userL.setText(model.getValueAt(i,1).toString());
        biosL.setText(model.getValueAt(i,2).toString());
        filmL.setText(model.getValueAt(i,3).toString());
        studioL.setText(model.getValueAt(i,4).toString());
        tglL.setText(model.getValueAt(i,5).toString());
        jamL.setText(model.getValueAt(i,6).toString());
        kursiL.setText(model.getValueAt(i,8).toString()+model.getValueAt(i,9).toString());
        napesL.setText(model.getValueAt(i,7).toString());
        hrgL.setText(model.getValueAt(i,10).toString());
        statusL.setText(model.getValueAt(i,11).toString());
        if("NOT CONFIRM".equals(statusL.getText())){
            statusL.setForeground(Color.red);
        }else{
            statusL.setForeground(Color.blue);
        }
    }//GEN-LAST:event_tabelFilmMouseClicked

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        
        int jawab = JOptionPane.showOptionDialog(this, 
                        "Confirm Booking"
                        + "\n"
                        + "\n--------------------------------------"
                        + "\n"
                        + "\nUsername : " + userL.getText()
                        + "\nNama Pemesan : " + napesL.getText()
                        + "\nBioskop : " + biosL.getText()
                        + "\nFilm : " + filmL.getText()
                        + "\nStudio : " + studioL.getText()
                        + "\nTanggal : " + tglL.getText()
                        + "\nWaktu : " + jamL.getText()
                        + "\nKursi :" + kursiL.getText()
                        + "\nHarga : " + hrgL.getText()
                        
                        + "\nSTATUS : " + statusL.getText()
                        + "", "Confirm", 
                       
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
           Akses as  = new Akses(idL.getText(),namaAdmin, userL.getText(), napesL.getText(),biosL.getText(),studioL.getText(),filmL.getText(),kursiL.getText());          
            try {
                if (as.setConfirm(idL.getText())) {
                JOptionPane.showMessageDialog(null, "Berhasil Konfirmasi");
                as.masukkanDataHistory();
                }
        } catch (SQLException ex) {
         Logger.getLogger(DaftarBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     
        }       
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel biosL;
    private javax.swing.JPanel biosPanel;
    private javax.swing.JButton bioskop1;
    private javax.swing.JButton bioskop2;
    private javax.swing.JButton bioskop3;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel filmL;
    private javax.swing.JPanel filmPanel;
    private javax.swing.JLabel hrgL;
    private javax.swing.JLabel idL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jamL;
    private javax.swing.JLabel kursiL;
    private javax.swing.JLabel namaBios;
    private javax.swing.JLabel napesL;
    private javax.swing.JLabel statusL;
    private javax.swing.JButton studio1;
    private javax.swing.JButton studio2;
    private javax.swing.JButton studio3;
    private javax.swing.JLabel studioL;
    private javax.swing.JTable tabelFilm;
    private javax.swing.JLabel tglL;
    private javax.swing.JLabel userL;
    // End of variables declaration//GEN-END:variables
}
