/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uas.bioskopapp.admin;

import com.uas.bioskopapp.admin.connect.Konek;
import com.uas.bioskopapp.admin.kelas.Akses;
import com.uas.bioskopapp.admin.kelas.EditClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author User
 */
public class Edit extends javax.swing.JFrame {

    private String username, pass,namaAdmin, noStudio;
    private String tanggal;
    private Statement ks;
    private ResultSet Rslogin;
    private String sql="";
    private ResultSet Rs;
    public int[] bangku = new int[12];
            private Connection koneksi;
    private Statement cs;
    private Konek kdb = new Konek();
    /**
     * Creates new form DaftarBooking
     */
    public Edit() {
        initComponents();

        
        studio1.setVisible(false);
        studio2.setVisible(false);
        studio3.setVisible(false);
    

    }

    void namauser(String nama, String password) {
            
            
            try {
            sql = "select * from admin where username='"+nama+"'"
            + "and password='"+password+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rslogin = cs.executeQuery(sql);
            if(Rslogin.next()){
            username = Rslogin.getString("username");
            pass = Rslogin.getString("password");
            namaAdmin = Rslogin.getString("nama");
            }else{
                System.out.println("Tidak ada username");
            }
            } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
                           
    }
    
    void dataTable(DefaultTableModel tabel1, JTable table2){
        tabel1.addColumn("Bioskop");
        tabel1.addColumn("Film"); 
        tabel1.addColumn("Studio");
        tabel1.addColumn("Genre");
        tabel1.addColumn("Durasi");
        tabel1.addColumn("Tanggal"); 
        tabel1.addColumn("Jam"); 
        
        table2.setModel(tabel1);
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        biosPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        bioskop1 = new javax.swing.JButton();
        bioskop2 = new javax.swing.JButton();
        bioskop3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filmPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        biosL = new javax.swing.JLabel();
        studioL = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        tanggalDate = new com.toedter.calendar.JDateChooser("yyyy-MM-dd", "####-##-##", '_');
        filmTf = new javax.swing.JTextField();
        genreTf = new javax.swing.JTextField();
        durasiTf = new javax.swing.JTextField();
        jamTf = new javax.swing.JTextField();
        kursiBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namaBios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studio1 = new javax.swing.JButton();
        studio2 = new javax.swing.JButton();
        studio3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        biosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        bioskop1.setText("AMBARRUKMO XXI");
        bioskop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop1ActionPerformed(evt);
            }
        });

        bioskop2.setText("EMPIRE XXI");
        bioskop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop2ActionPerformed(evt);
            }
        });

        bioskop3.setText("JOGJA CITY XXI");
        bioskop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskop3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bioskop :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn)
                    .addComponent(bioskop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addComponent(bioskop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bioskop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bioskop1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioskop2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bioskop3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Bioskop");

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", null, "-", "-"}
            },
            new String [] {
                "Bioskop", "Film", "Studio", "Genre", "Durasi", "Tanggal", "Jam"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelFilm);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bioskop :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Film :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Studio :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tanggal :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Jam :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Genre :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Kursi :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Durasi :");

        biosL.setText("-");

        studioL.setText("-");

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        kursiBtn.setText("Lihat");
        kursiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filmPanelLayout = new javax.swing.GroupLayout(filmPanel);
        filmPanel.setLayout(filmPanelLayout);
        filmPanelLayout.setHorizontalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(biosL, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filmTf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studioL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(filmPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(durasiTf))
                                    .addGroup(filmPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genreTf))))
                            .addGroup(filmPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kursiBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filmPanelLayout.createSequentialGroup()
                                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jamTf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filmPanelLayout.createSequentialGroup()
                                .addComponent(UpdateBtn)
                                .addContainerGap())))))
        );
        filmPanelLayout.setVerticalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(biosL)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8)
                        .addComponent(filmTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(studioL)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(genreTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(durasiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursiBtn)
                            .addComponent(jLabel13)))
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bioskop : ");

        namaBios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaBios.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Studio :");

        studio1.setText("Studio1");
        studio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio1ActionPerformed(evt);
            }
        });

        studio2.setText("Studio2");
        studio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio2ActionPerformed(evt);
            }
        });

        studio3.setText("Studio3");
        studio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studio3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout biosPanelLayout = new javax.swing.GroupLayout(biosPanel);
        biosPanel.setLayout(biosPanelLayout);
        biosPanelLayout.setHorizontalGroup(
            biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biosPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biosPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaBios, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(studio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studio3)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(312, 312, 312))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biosPanelLayout.createSequentialGroup()
                                .addComponent(filmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))))
        );
        biosPanelLayout.setVerticalGroup(
            biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(biosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(biosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studio1)
                    .addComponent(jLabel4)
                    .addComponent(studio2)
                    .addComponent(studio3)
                    .addComponent(namaBios)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(filmPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(biosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(biosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio3ActionPerformed
        // TODO add your handling code here:
        biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        noStudio = "3";
        filmPanel.setBackground(Color.orange);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
        try{

            sql="SELECT bioskop.nama_bioskop, film.nama_film, studio.no_studio, film.genre, film.durasi , studio.tanggal , studio.jam_mulai "
                + "FROM bioskop INNER JOIN studio ON bioskop.id_bioskop=studio.id_bioskop INNER JOIN film ON film.id_film=studio.id_film INNER JOIN bangku ON bangku.id_bangku=studio.id_bangku "
                + "WHERE bioskop.nama_bioskop LIKE '"+namaBios.getText() +"' AND studio.no_studio ='"+noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),


                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio3ActionPerformed

    private void studio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio2ActionPerformed
        // TODO add your handling code here:
        noStudio = "2";
                biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        filmPanel.setBackground(Color.LIGHT_GRAY);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
        try{

            sql="SELECT bioskop.nama_bioskop, film.nama_film, studio.no_studio, film.genre, film.durasi , studio.tanggal , studio.jam_mulai "
                + "FROM bioskop INNER JOIN studio ON bioskop.id_bioskop=studio.id_bioskop INNER JOIN film ON film.id_film=studio.id_film INNER JOIN bangku ON bangku.id_bangku=studio.id_bangku "
                + "WHERE bioskop.nama_bioskop LIKE '"+namaBios.getText() +"' AND studio.no_studio ='"+noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),


                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio2ActionPerformed

    private void studio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studio1ActionPerformed
        // TODO add your handling code here:
                biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        noStudio = "1";
        filmPanel.setBackground(Color.white);
        DefaultTableModel tableBioskop1 = new DefaultTableModel();
        dataTable(tableBioskop1,tabelFilm);
       try{

            sql="SELECT bioskop.nama_bioskop, film.nama_film, studio.no_studio, film.genre, film.durasi , studio.tanggal , studio.jam_mulai "
                + "FROM bioskop INNER JOIN studio ON bioskop.id_bioskop=studio.id_bioskop INNER JOIN film ON film.id_film=studio.id_film INNER JOIN bangku ON bangku.id_bangku=studio.id_bangku "
                + "WHERE bioskop.nama_bioskop LIKE '"+namaBios.getText() +"' AND studio.no_studio ='"+noStudio+"'";
            kdb.bukaKoneksi();
            koneksi = kdb.getConn();
            cs = koneksi.createStatement();
            Rs = cs.executeQuery(sql);

            while (Rs.next())
            {
                tableBioskop1.addRow(new Object[]{
                    Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),


                });
            }

        }catch (SQLException e){
        }
        tabelFilm.setModel(tableBioskop1);
    }//GEN-LAST:event_studio1ActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:

        Date date = tanggalDate.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
        int jawab = JOptionPane.showOptionDialog(this,
            "Update"
            + "\n"
            + "\n--------------------------------------"
            + "\n"

            + "\nBioskop : " + biosL.getText()
            + "\nFilm : " + filmTf.getText()
            + "\nStudio : " + studioL.getText()
            + "\nTanggal : " + strDate
            + "\nWaktu : " + jamTf.getText()
            + "\nGenre :" + genreTf.getText()
            + "\nDurasi : " + durasiTf.getText()
            + "", "Confirm",

            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, null, null);

        if(jawab == JOptionPane.YES_OPTION){
            EditClass ec  = new EditClass(biosL.getText(),studioL.getText(), filmTf.getText(),genreTf.getText(),durasiTf.getText(),tanggalDate ,jamTf.getText());          
            try {
                ec.setConfirm(biosL.getText(), noStudio);
                ec.resetBangku(biosL.getText(),noStudio);
                ec.hapusPesan(biosL.getText(), noStudio);
                
                
                
        } catch (SQLException ex) {
         Logger.getLogger(DaftarBooking.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void tabelFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelFilmMouseClicked
        // TODO add your handling code here:
        UpdateBtn.setEnabled(true);
        int i = tabelFilm.getSelectedRow();
        TableModel model = tabelFilm.getModel();
        biosL.setText(model.getValueAt(i,0).toString());
        filmTf.setText(model.getValueAt(i,1).toString());
        studioL.setText(model.getValueAt(i,2).toString());
        genreTf.setText(model.getValueAt(i,3).toString());
        durasiTf.setText(model.getValueAt(i,4).toString());
        

        java.util.Date date;
     try {
         date = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i,5).toString());
         tanggalDate.setDate( date);
     } catch (ParseException ex) {
         Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
        jamTf.setText(model.getValueAt(i,6).toString());

    }//GEN-LAST:event_tabelFilmMouseClicked

    private void bioskop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop3ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
                biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        biosPanel.setBackground(Color.pink);
        namaBios.setText("JOGJA CITY XXI");
        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));

    }//GEN-LAST:event_bioskop3ActionPerformed

    private void bioskop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop2ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
                biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        biosPanel.setBackground(Color.yellow);
        namaBios.setText("EMPIRE XXI");
        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));

    }//GEN-LAST:event_bioskop2ActionPerformed

    private void bioskop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskop1ActionPerformed
        // TODO add your handling code here:
        studio1.setVisible(true);
        studio2.setVisible(true);
        studio3.setVisible(true);
        biosL.setText("");
        studioL.setText("");
        filmTf.setText("");
        durasiTf.setText("");
        genreTf.setText("");
        jamTf.setText("");
        UpdateBtn.setEnabled(false);
        biosPanel.setBackground(Color.green);
        namaBios.setText("AMBARRUKMO XXI");
        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"}
            },
            new String [] {
                "ID", "Username", "Bioskop", "Film", "Studio", "Tanggal", "Jam", "Nama Pemesan", "Baris", "Nomor", "Harga", "Status"
            }
        ));

    }//GEN-LAST:event_bioskop1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.namauser(username, pass);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void kursiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursiBtnActionPerformed
        // TODO add your handling code here:
                LihatBangku lb = new LihatBangku();
        lb.setVisible(true);
        lb.getDataBangku(studioL.getText(),biosL.getText(), bangku);
        
        
    }//GEN-LAST:event_kursiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel biosL;
    private javax.swing.JPanel biosPanel;
    private javax.swing.JButton bioskop1;
    private javax.swing.JButton bioskop2;
    private javax.swing.JButton bioskop3;
    private javax.swing.JTextField durasiTf;
    private javax.swing.JPanel filmPanel;
    private javax.swing.JTextField filmTf;
    private javax.swing.JTextField genreTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jamTf;
    private javax.swing.JButton kursiBtn;
    private javax.swing.JLabel namaBios;
    private javax.swing.JButton studio1;
    private javax.swing.JButton studio2;
    private javax.swing.JButton studio3;
    private javax.swing.JLabel studioL;
    private javax.swing.JTable tabelFilm;
    private com.toedter.calendar.JDateChooser tanggalDate;
    // End of variables declaration//GEN-END:variables
  
}
